import { Realm, ArcherBow } from '../types/game';

export const GAME_REALMS: Realm[] = [
  {
    id: 'realm_1',
    title: 'جنگل کلمات',
    englishTitle: 'Word Forest',
    subtitle: 'سرزمین زمزمه درختان کهن و نشانه‌های جادویی',
    description: 'در این جنگل باستانی، حروف س، ص و ث در میان درختان بلوط کهنسال و آبشارهای زمردین پنهان شده‌اند. کمان خود را آماده کن!',
    bgTheme: 'forest',
    primaryColor: '#10b981',
    accentColor: '#34d399',
    levels: [
      {
        id: 'r1_l1',
        realmId: 'realm_1',
        levelNumber: 1,
        title: 'ردپای حروف در بیشه',
        description: 'شکار واژگان با املای صحیح «س / ص / ث»',
        mode: 'word_hunt',
        targetCount: 4,
        category: 's_s_th',
        grade: 'grade_1_2',
        difficulty: 1,
        requiredScore: 300,
        starsEarned: 0,
        isUnlocked: true,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r1_l2',
        realmId: 'realm_1',
        levelNumber: 2,
        title: 'تیر بر حرف گمشده',
        description: 'حرف گم‌شده را از بین رون‌های چرخان هدف بگیر',
        mode: 'letter_snipe',
        targetCount: 4,
        category: 's_s_th',
        grade: 'grade_1_2',
        difficulty: 1,
        requiredScore: 350,
        starsEarned: 0,
        isUnlocked: true,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r1_l3',
        realmId: 'realm_1',
        levelNumber: 3,
        title: 'نجات واژه از کمینگاه',
        description: 'شکستن سپرهای غلط برای نجات کلمه اسیر',
        mode: 'word_rescue',
        targetCount: 3,
        category: 's_s_th',
        grade: 'grade_3_4',
        difficulty: 1,
        requiredScore: 400,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r1_l4',
        realmId: 'realm_1',
        levelNumber: 4,
        title: 'پاکسازی بچه هیولا',
        description: 'شلیک به کلمه غلط‌نویسی شده و تبدیل هیولا به روح آرامش',
        mode: 'monster_combat',
        targetCount: 4,
        category: 's_s_th',
        grade: 'grade_3_4',
        difficulty: 2,
        requiredScore: 500,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
    ],
  },
  {
    id: 'realm_2',
    title: 'غار بلورین حروف',
    englishTitle: 'Crystal Cave of Letters',
    subtitle: 'دنیای کریستال‌های چهارگانه ز، ض، ظ و ذ',
    description: 'در ژرفای این غار اسرارآمیز، بلورهای درخشان انعکاس واژگان پرچالش فارسی را به نمایش می‌گذارند. دقت در نشانه‌گیری کلید بقاست.',
    bgTheme: 'crystal_cave',
    primaryColor: '#8b5cf6',
    accentColor: '#a78bfa',
    levels: [
      {
        id: 'r2_l1',
        realmId: 'realm_2',
        levelNumber: 1,
        title: 'رقص بلورهای چهارگانه',
        description: 'تشخیص دقیق واژگان با حروف «ز / ض / ظ / ذ»',
        mode: 'word_hunt',
        targetCount: 5,
        category: 'z_z_z_z',
        grade: 'grade_3_4',
        difficulty: 2,
        requiredScore: 500,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r2_l2',
        realmId: 'realm_2',
        levelNumber: 2,
        title: 'شکار سریع در تاریکی',
        description: 'پرتاب به سوی حروف گمشده روی کریستال‌های متحرک',
        mode: 'letter_snipe',
        targetCount: 4,
        category: 'z_z_z_z',
        grade: 'grade_3_4',
        difficulty: 2,
        requiredScore: 550,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r2_l3',
        realmId: 'realm_2',
        levelNumber: 3,
        title: 'نبرد هیولای غارنورد',
        description: 'شکار املای نادرست پیش از رسیدن هیولا به دروازه',
        mode: 'monster_combat',
        targetCount: 5,
        category: 'z_z_z_z',
        grade: 'grade_3_4',
        difficulty: 2,
        requiredScore: 600,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r2_l4',
        realmId: 'realm_2',
        levelNumber: 4,
        title: 'سرعت در دالان بلورها',
        description: 'پرتال‌های بلورین به سرعت باز و بسته می‌شوند!',
        mode: 'speed_rush',
        targetCount: 6,
        timeLimit: 45,
        category: 'z_z_z_z',
        grade: 'grade_5_6',
        difficulty: 2,
        requiredScore: 700,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
    ],
  },
  {
    id: 'realm_3',
    title: 'شهر معلق واژه‌ها',
    englishTitle: 'Sky City of Words',
    subtitle: 'بر فراز ابرها، قلمرو ت، ط، غ و ق',
    description: 'قصرهای باستانی شناور بر فراز ابرها که طومارهای کهن زبان پارسی در هوای آن به پرواز درآمده‌اند. گوش بسپار و با خرد شلیک کن.',
    bgTheme: 'sky_city',
    primaryColor: '#0ea5e9',
    accentColor: '#38bdf8',
    levels: [
      {
        id: 'r3_l1',
        realmId: 'realm_3',
        levelNumber: 1,
        title: 'زمزمه بادهای آسمانی',
        description: 'گوش دادن به صدای واژه و پرتاب به هدف درست بدون دیدن کلمه',
        mode: 'audio_whisper',
        targetCount: 4,
        category: 't_t',
        grade: 'grade_1_2',
        difficulty: 1,
        requiredScore: 500,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r3_l2',
        realmId: 'realm_3',
        levelNumber: 2,
        title: 'چالش مرغان سخنگو (ت / ط)',
        description: 'شکار اهداف متحرک هوایی با دقت بالا',
        mode: 'word_hunt',
        targetCount: 5,
        category: 't_t',
        grade: 'grade_3_4',
        difficulty: 2,
        requiredScore: 600,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r3_l3',
        realmId: 'realm_3',
        levelNumber: 3,
        title: 'آوای مرموز غین و قاف (غ / ق)',
        description: 'شنیدن تلفظ کلمات پرچالش غ و ق و شلیک هوشمندانه',
        mode: 'audio_whisper',
        targetCount: 5,
        category: 'gh_gh',
        grade: 'grade_3_4',
        difficulty: 2,
        requiredScore: 650,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r3_l4',
        realmId: 'realm_3',
        levelNumber: 4,
        title: 'رهایی کلمه بر فراز ابرها',
        description: 'آزادسازی کلمات اسیر در تله‌های طوفانی',
        mode: 'word_rescue',
        targetCount: 4,
        category: 'gh_gh',
        grade: 'grade_5_6',
        difficulty: 2,
        requiredScore: 700,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
    ],
  },
  {
    id: 'realm_4',
    title: 'قلعه غلط‌نویس',
    englishTitle: 'Fortress of the Misspeller',
    subtitle: 'آزمون سهمگین در دژ تاریک ه، ح و واو معدوله',
    description: 'دژی محاصره شده در آتش و دود که اشتباهات املایی در آن به غول‌های متخاصم بدل گشته‌اند. تنها یک تیرانداز چیره‌دست می‌تواند از این دژ عبور کند.',
    bgTheme: 'dark_fortress',
    primaryColor: '#f97316',
    accentColor: '#fb923c',
    levels: [
      {
        id: 'r4_l1',
        realmId: 'realm_4',
        levelNumber: 1,
        title: 'نبرد در شعله‌های آتش',
        description: 'تشخیص واژگان با «هـ / ح» و واو معدوله «خوا»',
        mode: 'word_hunt',
        targetCount: 5,
        category: 'khva',
        grade: 'grade_3_4',
        difficulty: 2,
        requiredScore: 650,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r4_l2',
        realmId: 'realm_4',
        levelNumber: 2,
        title: 'شکار هیولاهای دژبان',
        description: 'پاکسازی نگهبانان دژ با اصلاح خطاهای املایی',
        mode: 'monster_combat',
        targetCount: 5,
        category: 'h_h',
        grade: 'grade_3_4',
        difficulty: 2,
        requiredScore: 750,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r4_l3',
        realmId: 'realm_4',
        levelNumber: 3,
        title: 'طوفان زمان در دژ',
        description: 'شکار اهداف در حال فرار پیش از اتمام زمان',
        mode: 'speed_rush',
        targetCount: 7,
        timeLimit: 40,
        category: 'tashdid',
        grade: 'grade_5_6',
        difficulty: 3,
        requiredScore: 850,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
    ],
  },
  {
    id: 'realm_5',
    title: 'جزیره استادان املا',
    englishTitle: 'Sanctuary of Spelling Masters',
    subtitle: 'میدان نبرد نهایی با غول غلط‌نوشت‌خوار اعظم',
    description: 'سرزمین ابدی نور و شکوه ادب پارسی. در این محراب آسمانی باید با هیولای عظیم غلط‌نویس روبرو شوی و نشان طلایی استاد املا را به چنگ آوری!',
    bgTheme: 'celestial_island',
    primaryColor: '#eab308',
    accentColor: '#fde047',
    levels: [
      {
        id: 'r5_l1',
        realmId: 'realm_5',
        levelNumber: 1,
        title: 'محک مهارت جامع',
        description: 'ترکیب تمامی حروف و چالش‌های املایی کتاب‌های فارسی',
        mode: 'word_hunt',
        targetCount: 6,
        category: 'all',
        grade: 'all',
        difficulty: 3,
        requiredScore: 800,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r5_l2',
        realmId: 'realm_5',
        levelNumber: 2,
        title: 'نجات آخرین طومار کهن',
        description: 'شکستن زنجیرهای طلسم و آزاد کردن کلمات ناب',
        mode: 'word_rescue',
        targetCount: 5,
        category: 'all',
        grade: 'all',
        difficulty: 3,
        requiredScore: 900,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
      {
        id: 'r5_l3',
        realmId: 'realm_5',
        levelNumber: 3,
        title: '👑 نبرد نهایی با هیولای غلط‌نویس',
        description: 'مبارزه چند مرحله‌ای حماسی با نابودگر غلط‌نویسی',
        mode: 'boss_battle',
        targetCount: 6,
        bossName: 'غول غلط‌نوشت‌خوار اعظم',
        bossMaxHealth: 6,
        category: 'all',
        grade: 'all',
        difficulty: 3,
        requiredScore: 1200,
        starsEarned: 0,
        isUnlocked: false,
        isCompleted: false,
        highScore: 0,
      },
    ],
  },
];

export const ARCHER_BOWS: ArcherBow[] = [
  {
    id: 'bow_apprentice',
    name: 'کمان چوبی نوآموز',
    description: 'کمان سبک و منعطف ساخته شده از چوب درخت گردو',
    drawSpeed: 1.0,
    arrowSpeed: 1.0,
    powerMultiplier: 1.0,
    glowColor: '#10b981',
    price: 0,
    isUnlocked: true,
    icon: '🪵',
  },
  {
    id: 'bow_simurgh',
    name: 'کمان بال سیمرغ',
    description: 'آمیخته با پرهای آتشین سیمرغ؛ سرعت کشش و برد پرتاب بالاتر',
    drawSpeed: 1.3,
    arrowSpeed: 1.3,
    powerMultiplier: 1.25,
    glowColor: '#f97316',
    price: 350,
    isUnlocked: false,
    icon: '🪶',
  },
  {
    id: 'bow_crystal',
    name: 'کمان بلورین آسمان',
    description: 'تراشیده از الماس غار بلورین با دقت نقطه‌زن شگفت‌انگیز',
    drawSpeed: 1.5,
    arrowSpeed: 1.5,
    powerMultiplier: 1.5,
    glowColor: '#38bdf8',
    price: 750,
    isUnlocked: false,
    icon: '💎',
  },
  {
    id: 'bow_arash',
    name: 'کمان زرین آرش کمانگیر',
    description: 'افسانه‌ای‌ترین سلاح ادب پارسی با ردپای نور طلایی و قدرت بی‌نهایت',
    drawSpeed: 1.8,
    arrowSpeed: 1.8,
    powerMultiplier: 2.0,
    glowColor: '#eab308',
    price: 1500,
    isUnlocked: false,
    icon: '🏹',
  },
];
